module.exports = {
  parser: 'babel-eslint',
  extends: 'dave/react',
  globals: {
    $About: true,
  },
  rules: {
    'max-len': ['error', { code: 90 }],
    'no-extra-parens': 'error',
    'no-template-curly-in-string': 'error',
    'no-eval': 'error',
    'no-alert': 'error',
    'no-caller': 'error',
    'guard-for-in': 'error',
    'eqeqeq': 'error',
    'dot-notation': 'error',
    'curly': ['error', 'all'],
    'consistent-return': 'error',
    'no-proto': 'error',
    'no-octal-escape': 'error',
    'no-multi-spaces': 'error',
    'no-iterator': 'error',
    'no-extend-native': 'error',
    'no-extra-label': 'error',
    'no-floating-decimal': 'error',
    'no-lone-blocks': 'error',
    'no-script-url': 'error',
    'no-sequences': 'error',
    'no-useless-call': 'error',
    'no-unused-expressions': 'error',
    'no-throw-literal': 'error',
    'no-unmodified-loop-condition': 'error',
    'no-useless-concat': 'error',
    'no-useless-catch': 'error',
    'no-void': 'error',
    'no-with': 'error',
    'no-label-var': 'error',
    'no-restricted-globals': 'error',
    'no-shadow': 'error',
    'no-undef-init': 'error',
    'no-use-before-define': 'error',
    'block-spacing': 'error',
    'brace-style': ['error', '1tbs'],
    'camelcase': 'error',
    'no-new-object': 'error',
    'spaced-comment': ['error', 'always', { 'exceptions': ['-', '+'] }],
    'prefer-object-spread': 'error',
    'no-trailing-spaces': 'error',
    'space-infix-ops': 'error',
  },
  settings: {
    react: {
      version: 'detect',
    },
  },
};
